--------
       0:   enter                   6, vars(4), args(4)
gc-start.
  * stack: 5
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 0, buf(0)
  * stack: 5
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 0, buf(0)
gc-done.
capacity = 11, size = 6
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:4)
   * (int) 2
   * (int) 1
   * (und) null
   * (und) null
exception size = 0.
print_stack done.
goto next.
--------
       1:   pushi                   10
gc-start.
  * stack: 6
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 6
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
capacity = 11, size = 7
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:4)
   * (int) 2
   * (int) 1
   * (und) null
   * (und) null
[ 6] (int) 10
exception size = 0.
print_stack done.
goto next.
--------
       2:   pushf                   (null) => .L0(f)
gc-start.
  * stack: 7
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 7
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
capacity = 11, size = 8
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:4)
   * (int) 2
   * (int) 1
   * (und) null
   * (und) null
[ 6] (int) 10
[ 7] (fnc) adr:15, lex:(frm:5)
exception size = 0.
print_stack done.
goto next.
--------
       3:   storevx                 $(0,0)
gc-start.
  * stack: 8
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 8
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
capacity = 11, size = 7
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:4)
   * (fnc) adr:15, lex:(frm:5)
   * (int) 1
   * (und) null
   * (und) null
[ 6] (int) 10
exception size = 0.
print_stack done.
goto next.
--------
       4:   pushf                   (null) => .L0(7)
gc-start.
  * stack: 7
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 7
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
capacity = 11, size = 8
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:4)
   * (fnc) adr:15, lex:(frm:5)
   * (int) 1
   * (und) null
   * (und) null
[ 6] (int) 10
[ 7] (fnc) adr:7, lex:(frm:5)
exception size = 0.
print_stack done.
goto next.
--------
       5:   call                    1
gc-start.
  * stack: 8
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 8
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
capacity = 11, size = 10
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:4)
   * (fnc) adr:15, lex:(frm:5)
   * (int) 1
   * (und) null
   * (und) null
[ 6] (int) 10
[ 7] (fnc) adr:7, lex:(frm:5)
[ 8] (int) 1
[ 9] (adr) 6
exception size = 0.
print_stack done.
goto next.
--------
       7:   enter                   10, vars(4), args(4)
gc-start.
  * stack: 10
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 10
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
capacity = 20, size = 11
frmv = 10, lexv = 5
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:4)
   * (fnc) adr:15, lex:(frm:5)
   * (int) 1
   * (und) null
   * (und) null
[ 6] (int) 10
[ 7] (fnc) adr:7, lex:(frm:5)
[ 8] (int) 1
[ 9] (adr) 6
[10] (frm:10, vars:4) -> lex:(frm:5)
   * (int) 10
   * (und) null
   * (und) null
   * (und) null
exception size = 0.
print_stack done.
goto next.
--------
       8:   pushi                   100
gc-start.
  * stack: 11
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 2, buf(0)
  * stack: 11
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 2, buf(0)
gc-done.
capacity = 20, size = 12
frmv = 10, lexv = 5
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:4)
   * (fnc) adr:15, lex:(frm:5)
   * (int) 1
   * (und) null
   * (und) null
[ 6] (int) 10
[ 7] (fnc) adr:7, lex:(frm:5)
[ 8] (int) 1
[ 9] (adr) 6
[10] (frm:10, vars:4) -> lex:(frm:5)
   * (int) 10
   * (und) null
   * (und) null
   * (und) null
[11] (int) 100
exception size = 0.
print_stack done.
goto next.
--------
       9:   pushi                   10
gc-start.
  * stack: 12
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 2, buf(0)
  * stack: 12
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 2, buf(0)
gc-done.
capacity = 20, size = 13
frmv = 10, lexv = 5
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:4)
   * (fnc) adr:15, lex:(frm:5)
   * (int) 1
   * (und) null
   * (und) null
[ 6] (int) 10
[ 7] (fnc) adr:7, lex:(frm:5)
[ 8] (int) 1
[ 9] (adr) 6
[10] (frm:10, vars:4) -> lex:(frm:5)
   * (int) 10
   * (und) null
   * (und) null
   * (und) null
[11] (int) 100
[12] (int) 10
exception size = 0.
print_stack done.
goto next.
--------
       a:   pushvl1                 $1(0)
gc-start.
  * stack: 13
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 2, buf(0)
  * stack: 13
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 2, buf(0)
gc-done.
capacity = 20, size = 14
frmv = 10, lexv = 5
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:4)
   * (fnc) adr:15, lex:(frm:5)
   * (int) 1
   * (und) null
   * (und) null
[ 6] (int) 10
[ 7] (fnc) adr:7, lex:(frm:5)
[ 8] (int) 1
[ 9] (adr) 6
[10] (frm:10, vars:4) -> lex:(frm:5)
   * (int) 10
   * (und) null
   * (und) null
   * (und) null
[11] (int) 100
[12] (int) 10
[13] (fnc) adr:15, lex:(frm:5)
exception size = 0.
print_stack done.
goto next.
--------
       b:   call                    2
gc-start.
  * stack: 14
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 2, buf(0)
  * stack: 14
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 2, buf(0)
gc-done.
capacity = 20, size = 16
frmv = 10, lexv = 5
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:4)
   * (fnc) adr:15, lex:(frm:5)
   * (int) 1
   * (und) null
   * (und) null
[ 6] (int) 10
[ 7] (fnc) adr:7, lex:(frm:5)
[ 8] (int) 1
[ 9] (adr) 6
[10] (frm:10, vars:4) -> lex:(frm:5)
   * (int) 10
   * (und) null
   * (und) null
   * (und) null
[11] (int) 100
[12] (int) 10
[13] (fnc) adr:15, lex:(frm:5)
[14] (int) 2
[15] (adr) 12
exception size = 0.
print_stack done.
goto next.
--------
       f:   enter                   10, vars(0), args(0)
gc-start.
  * stack: 16
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 2, buf(0)
  * stack: 16
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 2, buf(0)
gc-done.
capacity = 26, size = 17
frmv = 16, lexv = 5
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:4)
   * (fnc) adr:15, lex:(frm:5)
   * (int) 1
   * (und) null
   * (und) null
[ 6] (int) 10
[ 7] (fnc) adr:7, lex:(frm:5)
[ 8] (int) 1
[ 9] (adr) 6
[10] (frm:10, vars:4) -> lex:(frm:5)
   * (int) 10
   * (und) null
   * (und) null
   * (und) null
[11] (int) 100
[12] (int) 10
[13] (fnc) adr:15, lex:(frm:5)
[14] (int) 2
[15] (adr) 12
[16] (frm:16, vars:0) -> lex:(frm:5)
exception size = 0.
print_stack done.
goto next.
--------
      10:   reti                    200
gc-start.
  * stack: 17
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 3, buf(0)
  * stack: 17
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 3, buf(0)
gc-done.
capacity = 26, size = 12
frmv = 10, lexv = 5
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:4)
   * (fnc) adr:15, lex:(frm:5)
   * (int) 1
   * (und) null
   * (und) null
[ 6] (int) 10
[ 7] (fnc) adr:7, lex:(frm:5)
[ 8] (int) 1
[ 9] (adr) 6
[10] (frm:10, vars:4) -> lex:(frm:5)
   * (int) 10
   * (und) null
   * (und) null
   * (und) null
[11] (int) 200
exception size = 0.
print_stack done.
goto next.
--------
       c:   pushi                   10
gc-start.
  * stack: 12
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 3, buf(0)
  * stack: 12
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 2, buf(1)
gc-done.
capacity = 26, size = 13
frmv = 10, lexv = 5
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:4)
   * (fnc) adr:15, lex:(frm:5)
   * (int) 1
   * (und) null
   * (und) null
[ 6] (int) 10
[ 7] (fnc) adr:7, lex:(frm:5)
[ 8] (int) 1
[ 9] (adr) 6
[10] (frm:10, vars:4) -> lex:(frm:5)
   * (int) 10
   * (und) null
   * (und) null
   * (und) null
[11] (int) 200
[12] (int) 10
exception size = 0.
print_stack done.
goto next.
--------
       d:   callvl1                 $1(0), 1
gc-start.
  * stack: 13
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 2, buf(1)
  * stack: 13
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 2, buf(1)
gc-done.
capacity = 26, size = 16
frmv = 10, lexv = 5
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:4)
   * (fnc) adr:15, lex:(frm:5)
   * (int) 1
   * (und) null
   * (und) null
[ 6] (int) 10
[ 7] (fnc) adr:7, lex:(frm:5)
[ 8] (int) 1
[ 9] (adr) 6
[10] (frm:10, vars:4) -> lex:(frm:5)
   * (int) 10
   * (und) null
   * (und) null
   * (und) null
[11] (int) 200
[12] (int) 10
[13] (fnc) adr:15, lex:(frm:5)
[14] (int) 1
[15] (adr) 14
exception size = 0.
print_stack done.
goto next.
--------
       f:   enter                   10, vars(0), args(0)
gc-start.
  * stack: 16
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 2, buf(1)
  * stack: 16
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 2, buf(1)
gc-done.
capacity = 26, size = 17
frmv = 16, lexv = 5
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:4)
   * (fnc) adr:15, lex:(frm:5)
   * (int) 1
   * (und) null
   * (und) null
[ 6] (int) 10
[ 7] (fnc) adr:7, lex:(frm:5)
[ 8] (int) 1
[ 9] (adr) 6
[10] (frm:10, vars:4) -> lex:(frm:5)
   * (int) 10
   * (und) null
   * (und) null
   * (und) null
[11] (int) 200
[12] (int) 10
[13] (fnc) adr:15, lex:(frm:5)
[14] (int) 1
[15] (adr) 14
[16] (frm:16, vars:0) -> lex:(frm:5)
exception size = 0.
print_stack done.
goto next.
--------
      10:   reti                    200
gc-start.
  * stack: 17
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 3, buf(0)
  * stack: 17
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 3, buf(0)
gc-done.
capacity = 26, size = 13
frmv = 10, lexv = 5
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:4)
   * (fnc) adr:15, lex:(frm:5)
   * (int) 1
   * (und) null
   * (und) null
[ 6] (int) 10
[ 7] (fnc) adr:7, lex:(frm:5)
[ 8] (int) 1
[ 9] (adr) 6
[10] (frm:10, vars:4) -> lex:(frm:5)
   * (int) 10
   * (und) null
   * (und) null
   * (und) null
[11] (int) 200
[12] (int) 200
exception size = 0.
print_stack done.
goto next.
--------
       e:   ret                    
gc-start.
  * stack: 13
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 3, buf(0)
  * stack: 13
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 2, buf(1)
gc-done.
capacity = 26, size = 7
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:4)
   * (fnc) adr:15, lex:(frm:5)
   * (int) 1
   * (und) null
   * (und) null
[ 6] (int) 200
exception size = 0.
print_stack done.
goto next.
--------
       6:   halt
gc-start.
  * stack: 7
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 3, buf(0)
    alive(frm) = 2, buf(1)
  * stack: 7
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(1)
    alive(frm) = 1, buf(2)
gc-done.
