--------
       0:   nop
gc-start.
  * stack: 5
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 0, buf(0)
  * stack: 5
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 0, buf(0)
gc-done.
capacity = 5, size = 5
frmv = -1, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 7
exception size = 0.
print_stack done.
goto next.
--------
       1:   nop
gc-start.
  * stack: 5
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 0, buf(0)
  * stack: 5
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 0, buf(0)
gc-done.
capacity = 5, size = 5
frmv = -1, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 7
exception size = 0.
print_stack done.
goto next.
--------
       2:   halt
gc-start.
  * stack: 5
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 0, buf(0)
  * stack: 5
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 0, buf(0)
gc-done.
