--------
       0:   enter                   100, vars(10), args(10)
gc-start.
  * stack: 5
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 0, buf(0)
  * stack: 5
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 0, buf(0)
gc-done.
capacity = 105, size = 6
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 3
[ 5] (frm:5, vars:10)
   * (int) 2
   * (int) 1
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
exception size = 0.
print_stack done.
goto next.
--------
       1:   push(a)
gc-start.
  * stack: 6
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 6
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
capacity = 105, size = 7
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 3
[ 5] (frm:5, vars:10)
   * (int) 2
   * (int) 1
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
[ 6] (obj) props:0
exception size = 0.
print_stack done.
goto next.
--------
       2:   halt
gc-start.
  * stack: 7
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 1, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 7
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 1, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
