--------
       0:   enter                   101, vars(10), args(10)
gc-start.
  * stack: 5
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 0, buf(0)
  * stack: 5
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 0, buf(0)
gc-done.
capacity = 106, size = 6
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:10)
   * (int) 2
   * (int) 1
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
exception size = 0.
print_stack done.
goto next.
--------
       1:   pushi                   100
gc-start.
  * stack: 6
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 6
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
capacity = 106, size = 7
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:10)
   * (int) 2
   * (int) 1
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
[ 6] (int) 100
exception size = 0.
print_stack done.
goto next.
--------
       2:   storevx                 $(0,0)
gc-start.
  * stack: 7
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 7
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
capacity = 106, size = 6
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:10)
   * (int) 100
   * (int) 1
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
exception size = 0.
print_stack done.
goto next.
--------
       3:   pushd                   9.900000
gc-start.
  * stack: 6
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 6
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
capacity = 106, size = 7
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:10)
   * (int) 100
   * (int) 1
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
[ 6] (dbl) 9.900000
exception size = 0.
print_stack done.
goto next.
--------
       4:   pushl                   $(0,1)
gc-start.
  * stack: 7
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 7
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
capacity = 106, size = 8
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:10)
   * (int) 100
   * (int) 1
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
[ 6] (dbl) 9.900000
[ 7] (lval) (frm:5)->var[1]
   * (int) 1
exception size = 0.
print_stack done.
goto next.
--------
       5:   store
gc-start.
  * stack: 8
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 8
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
capacity = 106, size = 7
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:10)
   * (int) 100
   * (dbl) 9.900000
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
[ 6] (dbl) 9.900000
exception size = 0.
print_stack done.
goto next.
--------
       6:   storev                  $(0,2)
gc-start.
  * stack: 7
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 7
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
capacity = 106, size = 7
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:10)
   * (int) 100
   * (dbl) 9.900000
   * (dbl) 9.900000
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
[ 6] (dbl) 9.900000
exception size = 0.
print_stack done.
goto next.
--------
       7:   pushl                   $(0,3)
gc-start.
  * stack: 7
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 7
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
capacity = 106, size = 8
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:10)
   * (int) 100
   * (dbl) 9.900000
   * (dbl) 9.900000
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
[ 6] (dbl) 9.900000
[ 7] (lval) (frm:5)->var[3]
   * (und) null
exception size = 0.
print_stack done.
goto next.
--------
       8:   storex
gc-start.
  * stack: 8
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 8
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
capacity = 106, size = 6
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:10)
   * (int) 100
   * (dbl) 9.900000
   * (dbl) 9.900000
   * (dbl) 9.900000
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
exception size = 0.
print_stack done.
goto next.
--------
       9:   pushs                   "xxxxxx"
gc-start.
  * stack: 6
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 6
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
capacity = 106, size = 7
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:10)
   * (int) 100
   * (dbl) 9.900000
   * (dbl) 9.900000
   * (dbl) 9.900000
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
[ 6] (cstr) xxxxxx
exception size = 0.
print_stack done.
goto next.
--------
       a:   storevx                 $(0,4)
gc-start.
  * stack: 7
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 7
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
capacity = 106, size = 6
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:10)
   * (int) 100
   * (dbl) 9.900000
   * (dbl) 9.900000
   * (dbl) 9.900000
   * (cstr) xxxxxx
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
exception size = 0.
print_stack done.
goto next.
--------
       b:   pushv                   $(0,0)
gc-start.
  * stack: 6
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 6
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
capacity = 106, size = 7
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:10)
   * (int) 100
   * (dbl) 9.900000
   * (dbl) 9.900000
   * (dbl) 9.900000
   * (cstr) xxxxxx
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
[ 6] (int) 100
exception size = 0.
print_stack done.
goto next.
--------
       c:   pushv                   $(0,1)
gc-start.
  * stack: 7
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 7
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
capacity = 106, size = 8
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:10)
   * (int) 100
   * (dbl) 9.900000
   * (dbl) 9.900000
   * (dbl) 9.900000
   * (cstr) xxxxxx
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
[ 6] (int) 100
[ 7] (dbl) 9.900000
exception size = 0.
print_stack done.
goto next.
--------
       d:   pushv                   $(0,2)
gc-start.
  * stack: 8
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 8
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
capacity = 106, size = 9
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:10)
   * (int) 100
   * (dbl) 9.900000
   * (dbl) 9.900000
   * (dbl) 9.900000
   * (cstr) xxxxxx
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
[ 6] (int) 100
[ 7] (dbl) 9.900000
[ 8] (dbl) 9.900000
exception size = 0.
print_stack done.
goto next.
--------
       e:   pushv                   $(0,3)
gc-start.
  * stack: 9
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 9
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
capacity = 106, size = 10
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:10)
   * (int) 100
   * (dbl) 9.900000
   * (dbl) 9.900000
   * (dbl) 9.900000
   * (cstr) xxxxxx
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
[ 6] (int) 100
[ 7] (dbl) 9.900000
[ 8] (dbl) 9.900000
[ 9] (dbl) 9.900000
exception size = 0.
print_stack done.
goto next.
--------
       f:   pushv                   $(0,4)
gc-start.
  * stack: 10
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 10
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
capacity = 106, size = 11
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 17
[ 5] (frm:5, vars:10)
   * (int) 100
   * (dbl) 9.900000
   * (dbl) 9.900000
   * (dbl) 9.900000
   * (cstr) xxxxxx
   * (und) null
   * (und) null
   * (und) null
   * (und) null
   * (und) null
[ 6] (int) 100
[ 7] (dbl) 9.900000
[ 8] (dbl) 9.900000
[ 9] (dbl) 9.900000
[10] (cstr) xxxxxx
exception size = 0.
print_stack done.
goto next.
--------
      10:   halt
gc-start.
  * stack: 11
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 11
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
