--------
       0:   enter                   5, vars(0), args(0)
gc-start.
  * stack: 5
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 0, buf(0)
  * stack: 5
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 0, buf(0)
gc-done.
capacity = 10, size = 6
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 18
[ 5] (frm:5, vars:0)
exception size = 0.
print_stack done.
goto next.
--------
       1:   pushf                   (null) => .L0(4)
gc-start.
  * stack: 6
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 6
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
capacity = 10, size = 7
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 18
[ 5] (frm:5, vars:0)
[ 6] (fnc) adr:4, lex:(frm:5)
exception size = 0.
print_stack done.
goto next.
--------
       2:   call                    0
gc-start.
  * stack: 7
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 7
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
capacity = 10, size = 9
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 18
[ 5] (frm:5, vars:0)
[ 6] (fnc) adr:4, lex:(frm:5)
[ 7] (int) 0
[ 8] (adr) 3
exception size = 0.
print_stack done.
goto next.
--------
       4:   enter                   9, vars(3), args(0)
gc-start.
  * stack: 9
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 1, buf(0)
  * stack: 9
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 1, buf(0)
gc-done.
capacity = 18, size = 10
frmv = 9, lexv = 5
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 18
[ 5] (frm:5, vars:0)
[ 6] (fnc) adr:4, lex:(frm:5)
[ 7] (int) 0
[ 8] (adr) 3
[ 9] (frm:9, vars:3) -> lex:(frm:5)
   * (und) null
   * (und) null
   * (und) null
exception size = 0.
print_stack done.
goto next.
--------
       5:   pushc                   .L0(e)
gc-start.
  * stack: 10
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 2, buf(0)
  * stack: 10
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 2, buf(0)
gc-done.
capacity = 18, size = 10
frmv = 9, lexv = 5
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 18
[ 5] (frm:5, vars:0)
[ 6] (fnc) adr:4, lex:(frm:5)
[ 7] (int) 0
[ 8] (adr) 3
[ 9] (frm:9, vars:3) -> lex:(frm:5)
   * (und) null
   * (und) null
   * (und) null
exception size = 1.
[ 0] sp = 10, adr = 14
print_stack done.
goto next.
--------
       6:   pushi                   1
gc-start.
  * stack: 10
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 2, buf(0)
  * stack: 10
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 2, buf(0)
gc-done.
capacity = 18, size = 11
frmv = 9, lexv = 5
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 18
[ 5] (frm:5, vars:0)
[ 6] (fnc) adr:4, lex:(frm:5)
[ 7] (int) 0
[ 8] (adr) 3
[ 9] (frm:9, vars:3) -> lex:(frm:5)
   * (und) null
   * (und) null
   * (und) null
[10] (int) 1
exception size = 1.
[ 0] sp = 10, adr = 14
print_stack done.
goto next.
--------
       7:   storevx                 $(0,0)
gc-start.
  * stack: 11
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 2, buf(0)
  * stack: 11
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 2, buf(0)
gc-done.
capacity = 18, size = 10
frmv = 9, lexv = 5
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 18
[ 5] (frm:5, vars:0)
[ 6] (fnc) adr:4, lex:(frm:5)
[ 7] (int) 0
[ 8] (adr) 3
[ 9] (frm:9, vars:3) -> lex:(frm:5)
   * (int) 1
   * (und) null
   * (und) null
exception size = 1.
[ 0] sp = 10, adr = 14
print_stack done.
goto next.
--------
       8:   pushi                   100
gc-start.
  * stack: 10
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 2, buf(0)
  * stack: 10
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 2, buf(0)
gc-done.
capacity = 18, size = 11
frmv = 9, lexv = 5
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 18
[ 5] (frm:5, vars:0)
[ 6] (fnc) adr:4, lex:(frm:5)
[ 7] (int) 0
[ 8] (adr) 3
[ 9] (frm:9, vars:3) -> lex:(frm:5)
   * (int) 1
   * (und) null
   * (und) null
[10] (int) 100
exception size = 1.
[ 0] sp = 10, adr = 14
print_stack done.
goto next.
--------
       9:   addv                    $(0,0)
gc-start.
  * stack: 11
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 2, buf(0)
  * stack: 11
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 2, buf(0)
gc-done.
capacity = 18, size = 11
frmv = 9, lexv = 5
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 18
[ 5] (frm:5, vars:0)
[ 6] (fnc) adr:4, lex:(frm:5)
[ 7] (int) 0
[ 8] (adr) 3
[ 9] (frm:9, vars:3) -> lex:(frm:5)
   * (int) 1
   * (und) null
   * (und) null
[10] (int) 101
exception size = 1.
[ 0] sp = 10, adr = 14
print_stack done.
goto next.
--------
       a:   storev                  $(0,1)
gc-start.
  * stack: 11
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 2, buf(0)
  * stack: 11
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 2, buf(0)
gc-done.
capacity = 18, size = 11
frmv = 9, lexv = 5
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 18
[ 5] (frm:5, vars:0)
[ 6] (fnc) adr:4, lex:(frm:5)
[ 7] (int) 0
[ 8] (adr) 3
[ 9] (frm:9, vars:3) -> lex:(frm:5)
   * (int) 1
   * (int) 101
   * (und) null
[10] (int) 101
exception size = 1.
[ 0] sp = 10, adr = 14
print_stack done.
goto next.
--------
       b:   throwe                  (stack-top)
gc-start.
  * stack: 11
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 2, buf(0)
  * stack: 11
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 2, buf(0)
gc-done.
capacity = 18, size = 11
frmv = 9, lexv = 5
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 18
[ 5] (frm:5, vars:0)
[ 6] (fnc) adr:4, lex:(frm:5)
[ 7] (int) 0
[ 8] (adr) 3
[ 9] (frm:9, vars:3) -> lex:(frm:5)
   * (int) 1
   * (int) 101
   * (und) null
[10] (int) 101
exception size = 0.
print_stack done.
goto next.
--------
       e:   catch                   $(0,2)
gc-start.
  * stack: 11
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 2, buf(0)
  * stack: 11
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 2, buf(0)
gc-done.
capacity = 18, size = 10
frmv = 9, lexv = 5
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 18
[ 5] (frm:5, vars:0)
[ 6] (fnc) adr:4, lex:(frm:5)
[ 7] (int) 0
[ 8] (adr) 3
[ 9] (frm:9, vars:3) -> lex:(frm:5)
   * (int) 1
   * (int) 101
   * (int) 101
exception size = 0.
print_stack done.
goto next.
--------
       f:   retvl                   $0(2)
gc-start.
  * stack: 10
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 2, buf(0)
  * stack: 10
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 2, buf(0)
gc-done.
capacity = 18, size = 7
frmv = 5, lexv = -1
[ 0] (int) 1
[ 1] (int) 2
[ 2] (fnc) adr:0, lex:(none)
[ 3] (int) 2
[ 4] (adr) 18
[ 5] (frm:5, vars:0)
[ 6] (int) 101
exception size = 0.
print_stack done.
goto next.
--------
       3:   halt
gc-start.
  * stack: 7
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 2, buf(0)
    alive(frm) = 2, buf(0)
  * stack: 7
    alive(str) = 0, buf(0)
    alive(big) = 0, buf(0)
    alive(obj) = 0, buf(0)
    alive(fnc) = 1, buf(1)
    alive(frm) = 1, buf(1)
gc-done.
