name: CI

jobs:
  build-windows-x64:
    name: windows-2019-vc
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          make.cmd
      - name: Create installer
        uses: joncloud/makensis-action@v3.4
      - name: package
        shell: pwsh
        run: Compress-Archive -Path kinx.exe,kxrepl.exe,kxtest.exe,kxkitty.exe,kx.lib,*.dll,lib/ -DestinationPath windows-x64.zip -Force -Verbose
      - name: upload archive
        uses: actions/upload-artifact@v1
        with:
          name: build-windows-x64
          path: |
            windows-x64.zip
            Kinx_installer_*.exe
